CREATE TABLE PROFESORES (
ID_PROFE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE VARCHAR2 (50) NOT NULL,
APELLIDOS VARCHAR2 (50) NOT NULL,
F_NACIMIENTO DATE 
);

CREATE TABLE CURSOS (
ID_CURSO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TITULO VARCHAR2 (50),
ID_PROFE NUMERIC,
CONSTRAINT FK_PROFE
FOREIGN KEY (ID_PROFE)
REFERENCES PROFESORES (ID_PROFE)
);

CREATE TABLE ALUMNOS (
ID_ALUMNO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NOMBRE VARCHAR2 (50) NOT NULL,
APELLIDOS VARCHAR2 (50) NOT NULL,
F_NACIMIENTO DATE 
);

CREATE TABLE ALUMNOS_CURSOS (
ID_ALUMNO NUMERIC,
ID_CURSO NUMERIC,

CONSTRAINT FK_ALUMNO
FOREIGN KEY (ID_ALUMNO)
REFERENCES ALUMNOS (ID_ALUMNO),
CONSTRAINT FK_CURSO
FOREIGN KEY (ID_CURSO)
REFERENCES CURSOS (ID_CURSO)
);