REM   Script: EXAMEN2
REM   HHHHHHH

SELECT C.ID_CURSO, C.TITULO, P.ID_PROFE, P.NOMBRE, P.APELLIDOS, P.F_NACIMIENTO 
FROM Cursos AS C 
JOIN Profesores AS P ON C.ID_PROFE = P.ID_PROFE;

SELECT A.ID_CURSO, A.TITULO, B.ID_PROFE, B.NOMBRE, B.APELLIDOS, B.F_NACIMIENTO 
FROM CURSOS AS INER JOIN PROFESORES AS NULL 
;

SELECT A.ID_CURSO, A.TITULO, B.ID_PROFE, B.NOMBRE, B.APELLIDOS, B.F_NACIMIENTO 
FROM Cursos AS A 
JOIN Profesores AS B ON A.ID_PROFE = B.ID_PROFE;

