CREATE TABLE PROFESORES (
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(50),
    FECHA_NACIMIENTO DATE
);


CREATE TABLE CURSOS (
    ID INT PRIMARY KEY,
    TITULO VARCHAR(50),
    ID_PROFE INT,
    FOREIGN KEY (ID_PROFE) REFERENCES PROFESORES(ID)
);


CREATE TABLE ALUMNOS (
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(50),
    FECHA_NACIMIENTO DATE
);

CREATE TABLE ALUMNOS (
    ID_ALUMNO INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(50),
    FECHA_NACIMIENTO DATE
);


CREATE TABLE ALUMNOS_CURSOS (
    ID_ALUMNO INT,
    ID_CURSO INT,
    PRIMARY KEY (ID_ALUMNO, ID_CURSO),
    FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS(ID_ALUMNO),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID)
);


