CREATE TABLE ALUMNOS (
    ID_ALUMNO INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(50),
    F_NACIMIENTO VARCHAR(10) 
);
CREATE TABLE PROFESORES (
    ID_PROFE INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(50),
    F_NACIMIENTO VARCHAR(10)  
);
CREATE TABLE CURSOS (
    ID_CURSO INT PRIMARY KEY,
    TITULO VARCHAR(50),
    ID_PROFE INT,
    FOREIGN KEY (ID_PROFE) REFERENCES PROFESORES(ID_PROFE)
);
CREATE TABLE ALUMNOS_CURSOS (
    ID_ALUMNO INT,
    ID_CURSO INT,
    PRIMARY KEY (ID_ALUMNO, ID_CURSO),
    FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS(ID_ALUMNO),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);