CREATE TABLE ESTUDIANTES(
ID NUMBER(5) PRIMARY KEY,
NOMBRE VARCHAR2 (40),
FECHA_NACIMIENTO DATE,
DIRECCION VARCHAR2 (100)
);

CREATE TABLE CURSOS(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(40),
CODIGO_CURSO VARCHAR2(100)
);

CREATE TABLE PROFESORES(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(40),
ESPECIALIDAD VARCHAR2(40)
);

CREATE TABLE INSCRIPCIONES(
FECHA_INSCRIPCION DATE,
CURSO_ID NUMBER,
ESTUDIANTE_ID NUMBER,
ID NUMBER PRIMARY KEY,
CONSTRAINT FK_ESTUDIANTE
FOREIGN KEY (ESTUDIANTE_ID)
REFERENCES ESTUDIANTES (ID),
CONSTRAINT FK_CURSOS 
FOREIGN KEY (CURSO_ID)
REFERENCES CURSOS (ID)
);





